#!/usr/bin/env node

/**
 * Static HTML generator for the colvmn layout engine.
 *
 * Walks the site tree, finds pages that use the layout engine (index.html with
 * a sibling _index.json or _index.md), and injects pre-rendered HTML into each
 * page. This makes content readable by AI crawlers and other clients that don't
 * execute JavaScript.
 *
 * The browser-side layout.js still runs and overwrites the static content on
 * load, so the two paths produce identical results.
 *
 * Usage:
 *   node colvmn/static-gen.js          # site root = parent of colvmn/ (submodule mode)
 *   node colvmn/static-gen.js <dir>    # site root = <dir> (explicit)
 *   node static-gen.js .               # self-host: colvmn is its own site root
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join, relative, dirname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

// Layout engine imports — same modules the browser uses
import { ContentBase } from "./layout/ContentBase.js";
import { ContentText } from "./layout/ContentText.js";
import { ContentCards } from "./layout/ContentCards.js";
import { ContentKeyValue } from "./layout/ContentKeyValue.js";
import { ContentUnorderedList } from "./layout/ContentUnorderedList.js";
import { ContentOrderedList } from "./layout/ContentOrderedList.js";
import { ContentTable } from "./layout/ContentTable.js";
import { ContentImage } from "./layout/ContentImage.js";
import { ContentTimeline } from "./layout/ContentTimeline.js";
import { ContentToc } from "./layout/ContentToc.js";
import { ContentFAQ } from "./layout/ContentFAQ.js";
import { ContentClassDoc } from "./layout/ContentClassDoc.js";
import { ContentCompetitorTable } from "./layout/ContentCompetitorTable.js";
import { PageIndex } from "./layout/PageIndex.js";
import { parseMarkdown } from "./layout/MarkdownParser.js";

// Register content types (mirrors layout.js)
ContentBase.typeMap = {
    ContentText,
    ContentCards,
    ContentKeyValue,
    ContentUnorderedList,
    ContentOrderedList,
    ContentTable,
    ContentImage,
    ContentTimeline,
    ContentToc,
    ContentFAQ,
    ContentClassDoc,
    ContentCompetitorTable,
};

const __dirname = dirname(fileURLToPath(import.meta.url));
// Default: colvmn lives at <siteRoot>/colvmn/ as a submodule.
// Override with argv[2] (e.g. "." to self-host colvmn's own pages).
const siteRoot = resolve(process.argv[2] || join(__dirname, ".."));

const skipDirs = new Set([
    "node_modules", "external-libs", "source", "build",
    "npm-pkg", "webserver", "resources", "colvmn",
]);

// ---------------------------------------------------------------------------
// Bundle generator — concatenates the ES-module sources into a single
// classic script. Chrome refuses to load <script type="module"> from file://,
// so generated pages reference this bundle instead of layout.js.
// ---------------------------------------------------------------------------

const BUNDLE_FILES = [
    "MarkdownParser.js",
    "ContentBase.js",
    "ContentText.js",
    "ContentCards.js",
    "ContentKeyValue.js",
    "ContentUnorderedList.js",
    "ContentOrderedList.js",
    "ContentTable.js",
    "ContentImage.js",
    "ContentTimeline.js",
    "ContentToc.js",
    "ContentFAQ.js",
    "ContentClassDoc.js",
    "ContentCompetitorTable.js",
    "PageIndex.js",
    "Lightbox.js",
    "layout.js",
];

// Escape `$` so a string can be safely used as the replacement argument
// to String.prototype.replace, where `$&`, `$<…>`, `$1`, etc. would
// otherwise be interpreted as backreferences. Rendered HTML can contain
// these sequences (e.g. a `$<` inside a code block becomes `$&lt;` after
// HTML-escaping, which expands to `[entire match]lt;` on replace).
function escapeReplacement (s) {
    return s.replace(/\$/g, "$$$$");
}

function transformBundleSource (src) {
    // Strip ES module import statements (single-line only — that's all colvmn uses).
    src = src.replace(/^[ \t]*import\b[^;\n]*;?\s*$/gm, "");
    // Drop the leading "export " on declarations so they become locals
    // shared across the IIFE scope.
    src = src.replace(/^([ \t]*)export\s+(class|function|const|let|var|async)\b/gm, "$1$2");
    // import.meta is a syntax error outside modules — substitute the script
    // URL captured at IIFE entry.
    src = src.replace(/\bimport\.meta\.url\b/g, "__COLVMN_SCRIPT_URL__");
    return src;
}

function buildBundle () {
    let bundle = "// Generated by colvmn/static-gen.js — do not edit by hand.\n";
    bundle += "(function(){\n\"use strict\";\n";
    bundle += "var __COLVMN_SCRIPT_URL__ = (typeof document !== 'undefined' && document.currentScript && document.currentScript.src) || (typeof window !== 'undefined' ? window.location.href : '');\n";
    for (const f of BUNDLE_FILES) {
        const src = readFileSync(join(__dirname, "layout", f), "utf-8");
        bundle += `\n// ===== ${f} =====\n` + transformBundleSource(src) + "\n";
    }
    bundle += "})();\n";
    return bundle;
}

// ---------------------------------------------------------------------------
// Filesystem-backed fetch that resolves URLs relative to a page directory
// ---------------------------------------------------------------------------

function createFetchFn (pageDir) {
    const cache = {};
    const fn = async function (url) {
        const decoded = decodeURIComponent(url);
        const filePath = resolve(pageDir, decoded);
        try {
            const content = readFileSync(filePath, "utf-8");
            cache[url] = { ok: true, status: 200, content };
            return {
                ok: true,
                status: 200,
                json: async () => JSON.parse(content),
                text: async () => content,
            };
        } catch {
            cache[url] = { ok: false, status: 404 };
            return { ok: false, status: 404 };
        }
    };
    fn.cache = cache;
    return fn;
}

// ---------------------------------------------------------------------------
// Directory walker — finds pages that have both index.html and _index content
// ---------------------------------------------------------------------------

function findLayoutPages (dir) {
    const pages = [];
    let entries;
    try {
        entries = readdirSync(dir, { withFileTypes: true });
    } catch {
        return pages;
    }

    const hasIndex = entries.some(e => e.name === "index.html" && e.isFile());
    const hasContent = entries.some(e =>
        (e.name === "_index.json" || e.name === "_index.md") && e.isFile()
    );

    if (hasIndex && hasContent) {
        pages.push(dir);
    }

    for (const entry of entries) {
        if (entry.isDirectory() && !entry.name.startsWith(".") && !skipDirs.has(entry.name)) {
            pages.push(...findLayoutPages(join(dir, entry.name)));
        }
    }

    return pages;
}

// ---------------------------------------------------------------------------
// Rewrite <link href> / <script src> targets that resolve to files inside
// the colvmn engine folder so they use a path relative to the page. This
// keeps the generated docs readable via file:// without a web server.
// ---------------------------------------------------------------------------

function rewriteEngineLinks (html, pageDir) {
    return html.replace(
        /(<(?:link|script)\b[^>]*\b(?:href|src)\s*=\s*)"([^"]+)"/gi,
        (match, prefix, urlValue) => {
            // Skip cross-origin URLs and protocol-relative URLs.
            if (/^[a-z][a-z0-9+.-]*:/i.test(urlValue) || urlValue.startsWith("//")) {
                return match;
            }
            // Skip fragment-only and query-only references.
            if (urlValue.startsWith("#") || urlValue.startsWith("?")) return match;

            // Resolve against siteRoot (server-absolute) or pageDir (relative).
            const absPath = urlValue.startsWith("/")
                ? resolve(siteRoot, urlValue.slice(1))
                : resolve(pageDir, urlValue);

            // Only rewrite assets that live inside the colvmn folder.
            const inColvmn = absPath === __dirname || absPath.startsWith(__dirname + sep);
            if (!inColvmn) return match;

            let relPath = relative(pageDir, absPath);
            if (!relPath) relPath = ".";
            relPath = relPath.split(sep).join("/");
            // Page-relative URLs that don't start with "../" need a "./" prefix.
            if (!relPath.startsWith(".")) relPath = "./" + relPath;
            return `${prefix}"${relPath}"`;
        }
    );
}

// ---------------------------------------------------------------------------
// Generate static HTML for a single page
// ---------------------------------------------------------------------------

async function generatePage (pageDir, siteUrl) {
    const relPath = relative(siteRoot, pageDir) || ".";
    const pathSegments = relPath === "."
        ? []
        : relPath.split(sep).filter(s => s.length > 0);

    const fetchFn = createFetchFn(pageDir);
    ContentBase.setFetchFn(fetchFn);

    const context = {
        isRoot: () => pageDir === siteRoot,
        pathSegments: () => pathSegments,
        urlParam: () => null,
    };

    const page = new PageIndex();
    await page.loadPage(context);

    if (!page.json) {
        console.log(`  skipped (no content): ${relPath}`);
        return;
    }

    const pageHtml = page.computePageHtml();
    const docTitle = page.computeDocumentTitle();

    // The "loaded" class is the contract with the browser runtime: PageIndex.render
    // skips HTML generation when it sees it, so the markup written here is the single
    // source of truth and the browser only runs the postRender behavior pass on top.
    // See colvmn/CLAUDE.md ("Rendering model").
    const pageClasses = ["page", "loaded"];
    if (page.json.pageLayout) {
        pageClasses.push(`page-${page.json.pageLayout}`);
    }

    // Read existing HTML template
    const htmlPath = join(pageDir, "index.html");
    let html = readFileSync(htmlPath, "utf-8");

    // Replace the .page div contents, or insert one if missing.
    // pageHtml is escaped because rendered content may contain `$&`/`$<…>`
    // sequences (e.g. `$<` in a Makefile code block escaped to `$&lt;`),
    // which String.prototype.replace would otherwise expand.
    const pageDiv = `<div class="${pageClasses.join(" ")}">${escapeReplacement(pageHtml)}</div>`;
    if (/(<body>\s*)<div class="page[^"]*"[^>]*>[\s\S]*<\/div>(\s*<script)/.test(html)) {
        html = html.replace(
            /(<body>\s*)<div class="page[^"]*"[^>]*>[\s\S]*<\/div>(\s*<script)/,
            `$1${pageDiv}$2`
        );
    } else {
        html = html.replace(
            /(<body>)\s*(\s*<script)/,
            `$1\n  ${pageDiv}\n$2`
        );
    }

    // Add or update <title> tag
    if (/<title>/.test(html)) {
        html = html.replace(/<title>[^<]*<\/title>/, `<title>${docTitle}</title>`);
    } else {
        html = html.replace("</head>", `  <title>${docTitle}</title>\n</head>`);
    }

    // Inject a <link rel="alternate"> pointing to /llms.txt so LLM agents
    // can discover the machine-readable index from any page. The href is
    // server-absolute here; rewriteEngineLinks() converts it to a page-
    // relative path below. The dedup check matches either form so repeated
    // builds don't accumulate duplicates.
    const llmsLinkTag = '<link rel="alternate" type="text/plain" title="llms.txt" href="/llms.txt">';
    if (!/<link\b[^>]*href="[^"]*\/?llms\.txt"/i.test(html) && /<\/head>/i.test(html)) {
        html = html.replace(/<\/head>/i, `  ${llmsLinkTag}\n</head>`);
    }

    // Canonical URL — directory form, not index.html. Only when siteUrl is
    // configured (llms-config.json { "siteUrl": "https://..." }).
    if (siteUrl && siteUrl !== "/") {
        const urlPath = relPath === "."
            ? ""
            : relPath.split(sep).map(s => encodeURIComponent(s)).join("/") + "/";
        const canonicalUrl = siteUrl + urlPath;
        const canonicalTag = `<link rel="canonical" href="${canonicalUrl}">`;
        if (html.includes('rel="canonical"')) {
            html = html.replace(/<link rel="canonical"[^>]*>/, canonicalTag);
        } else {
            html = html.replace(/<\/head>/i, `  ${canonicalTag}\n</head>`);
        }
    }

    // Meta description — use subtitle/intro text if available.
    const descriptionText = extractDescription(page.json);
    if (descriptionText) {
        // Escape for an HTML attribute value. Order matters: '&' first so we
        // don't double-escape the entities we introduce. Escaping '<' and '>'
        // (not just '"') is essential: static-gen reads its own prior output
        // as the page template, so an unescaped '>' in the description would
        // close the tag early and the leftover text would be re-emitted — and
        // accumulate — on every regen.
        const escapedDesc = descriptionText
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;");
        // escapeReplacement: descTag is used as a String.replace replacement
        // arg below, where any literal '$' would be read as a backreference.
        const descTag = escapeReplacement(`<meta name="description" content="${escapedDesc}">`);
        if (/<meta name="description"/.test(html)) {
            // Match the tag AND any trailing same-line junk (tags are emitted
            // one per line) so a previously-corrupted file self-heals on regen.
            html = html.replace(/<meta name="description"[^\n]*>/, descTag);
        } else {
            html = html.replace(/<\/head>/i, `  ${descTag}\n</head>`);
        }
    }

    // Rewrite engine asset URLs (style.css, layout.js, llms.txt, etc.) to
    // page-relative paths so the docs render correctly from file:// without
    // a web server. Done last so it also catches links injected above.
    html = rewriteEngineLinks(html, pageDir);

    // Swap the ES-module <script src="layout.js" type="module"> for a
    // classic deferred <script src="bundle.js">. Chrome blocks module
    // loading from file:// (CORS rules), so without this the page's JS
    // never runs and interactive bits like toggles do nothing.
    html = html.replace(
        /<script\b[^>]*\bsrc\s*=\s*"([^"]*colvmn\/layout\/(?:layout|bundle)\.js)"[^>]*>(\s*<\/script>)?/gi,
        (match, src) => {
            const newSrc = src.replace(/\/layout\.js$/, "/bundle.js");
            return `<script src="${newSrc}" defer></script>`;
        }
    );

    // Inline a prefetch cache of every URL the build fetched. The browser
    // checks this cache in ContentBase.asyncFetch before hitting fetch(),
    // so pages with dynamic content (toggles, etc.) work under file://
    // where fetch() of local files is blocked. Escape "<" so embedded JSON
    // can't terminate the script tag.
    const cacheJson = JSON.stringify(fetchFn.cache).replace(/</g, "\\u003c");
    const cacheTag = escapeReplacement(`<script type="application/json" id="colvmn-prefetch">${cacheJson}</script>`);
    if (/<script\b[^>]*\bid="colvmn-prefetch"[^>]*>[\s\S]*?<\/script>/.test(html)) {
        html = html.replace(/<script\b[^>]*\bid="colvmn-prefetch"[^>]*>[\s\S]*?<\/script>/, cacheTag);
    } else if (/<\/body>/i.test(html)) {
        html = html.replace(/<\/body>/i, `  ${cacheTag}\n</body>`);
    }

    writeFileSync(htmlPath, html);
    console.log(`  generated: ${relPath}`);
}

/**
 * Extract a short description from page JSON for the meta description tag.
 * Prefers the subtitle, falls back to the first paragraph of body content.
 * Truncates to 160 characters.
 */
function extractDescription (json) {
    if (!json) return "";

    if (json.subtitle) {
        return truncateDescription(htmlToPlain(json.subtitle));
    }

    for (const entry of json.content || []) {
        if (entry.type === "ContentText" && entry.body) {
            const plain = htmlToPlain(entry.body);
            if (plain) return truncateDescription(plain);
        }
    }

    return "";
}

function truncateDescription (text) {
    if (text.length <= 160) return text;
    const truncated = text.slice(0, 157);
    const lastSpace = truncated.lastIndexOf(" ");
    return (lastSpace > 100 ? truncated.slice(0, lastSpace) : truncated) + "...";
}

// ---------------------------------------------------------------------------
// Sitemap generator
// ---------------------------------------------------------------------------

function generateSitemap (pages, baseUrl) {
    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

    for (const pageDir of pages) {
        const relPath = relative(siteRoot, pageDir);
        const urlPath = relPath
            ? relPath.split(sep).map(s => encodeURIComponent(s)).join("/") + "/"
            : "";
        xml += `  <url><loc>${baseUrl}${urlPath}</loc></url>\n`;
    }

    xml += `  <url><loc>${baseUrl}llms.txt</loc></url>\n`;
    xml += `  <url><loc>${baseUrl}llms-full.txt</loc></url>\n`;
    xml += "</urlset>\n";
    return xml;
}

// ---------------------------------------------------------------------------
// llms.txt / llms-full.txt generation
// ---------------------------------------------------------------------------

function htmlToPlain (html) {
    if (!html) return "";
    return html
        .replace(/<br\s*\/?>/gi, " ")
        .replace(/<[^>]+>/g, "")
        .replace(/&nbsp;/g, " ")
        .replace(/&mdash;/g, "\u2014")
        .replace(/&ndash;/g, "\u2013")
        .replace(/&ldquo;/g, "\u201c").replace(/&rdquo;/g, "\u201d")
        .replace(/&lsquo;/g, "\u2018").replace(/&rsquo;/g, "\u2019")
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/\s+/g, " ")
        .trim();
}

function htmlToMarkdown (html) {
    if (!html) return "";
    let s = html;
    // Code blocks
    s = s.replace(/<pre><code>([\s\S]*?)<\/code><\/pre>/gi, (_, code) => `\n\`\`\`\n${code}\n\`\`\`\n`);
    // Headings (rare in bodies, but handle them)
    s = s.replace(/<h([1-6])[^>]*>([\s\S]*?)<\/h\1>/gi, (_, level, text) => `\n\n${"#".repeat(+level)} ${text.trim()}\n\n`);
    // Lists: open tag → newline; close tag → newline; items become "- item"
    s = s.replace(/<\/li>\s*<li[^>]*>/gi, "\n- ");
    s = s.replace(/<(ul|ol)[^>]*>\s*<li[^>]*>/gi, "\n- ");
    s = s.replace(/<\/li>\s*<\/(ul|ol)>/gi, "\n");
    s = s.replace(/<(ul|ol)[^>]*>/gi, "\n").replace(/<\/(ul|ol)>/gi, "\n");
    s = s.replace(/<li[^>]*>/gi, "- ").replace(/<\/li>/gi, "\n");
    // Inline formatting
    s = s.replace(/<a\s+[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi, "[$2]($1)");
    s = s.replace(/<(strong|b)>([\s\S]*?)<\/(strong|b)>/gi, "**$2**");
    s = s.replace(/<(em|i)>([\s\S]*?)<\/(em|i)>/gi, "*$2*");
    s = s.replace(/<code>([\s\S]*?)<\/code>/gi, "`$1`");
    // Paragraphs and breaks
    s = s.replace(/<p[^>]*>/gi, "").replace(/<\/p>/gi, "\n\n");
    s = s.replace(/<br\s*\/?>/gi, "\n");
    // Strip remaining tags
    s = s.replace(/<[^>]+>/g, "");
    // Entities
    s = s.replace(/&nbsp;/g, " ")
        .replace(/&mdash;/g, "\u2014")
        .replace(/&ndash;/g, "\u2013")
        .replace(/&ldquo;/g, "\u201c").replace(/&rdquo;/g, "\u201d")
        .replace(/&lsquo;/g, "\u2018").replace(/&rsquo;/g, "\u2019")
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">");
    s = s.replace(/\n{3,}/g, "\n\n");
    return s.trim();
}

function pageUrlPath (pageDir) {
    const relPath = relative(siteRoot, pageDir);
    if (!relPath) return "";
    return relPath.split(sep).map(s => encodeURIComponent(s)).join("/") + "/";
}

function readPageMeta (pageDir) {
    const jsonPath = join(pageDir, "_index.json");
    const mdPath = join(pageDir, "_index.md");

    if (existsSync(jsonPath)) {
        const json = JSON.parse(readFileSync(jsonPath, "utf-8"));
        return { json, rawMarkdown: null };
    }
    if (existsSync(mdPath)) {
        const raw = readFileSync(mdPath, "utf-8");
        return { json: parseMarkdown(raw), rawMarkdown: raw };
    }
    return null;
}

function pageDisplayTitle (pageDir, meta) {
    if (meta && meta.json && meta.json.title) return meta.json.title;
    const relPath = relative(siteRoot, pageDir);
    return relPath ? relPath.split(sep).pop() : "";
}

function contentEntryToMarkdown (entry, depth = 0) {
    const title = entry.title || "";
    const heading = depth === 0 ? "##" : "###";

    switch (entry.type) {
        case "ContentText": {
            let md = "";
            if (title) md += `${heading} ${title}\n\n`;
            if (entry.body) md += htmlToMarkdown(entry.body) + "\n\n";
            if (Array.isArray(entry.content)) {
                for (const child of entry.content) md += contentEntryToMarkdown(child, depth + 1);
            }
            return md;
        }
        case "ContentCards": {
            let md = "";
            if (title) md += `${heading} ${title}\n\n`;
            for (const item of entry.items || []) {
                if (typeof item === "string") {
                    md += `- ${item}\n`;
                } else {
                    let line = `- **${item.title || item.folder || ""}**`;
                    if (item.href) line = `- [${item.title || item.href}](${item.href})`;
                    if (item.date) line += ` (${item.date})`;
                    if (item.subtitle) line += ` — ${htmlToPlain(item.subtitle)}`;
                    md += line + "\n";
                }
            }
            return md + "\n";
        }
        case "ContentKeyValue": {
            let md = "";
            if (title) md += `${heading} ${title}\n\n`;
            for (const [k, v] of Object.entries(entry.items || {})) {
                md += `- **${k}**: ${htmlToPlain(String(v))}\n`;
            }
            return md + "\n";
        }
        case "ContentUnorderedList":
        case "ContentOrderedList": {
            let md = "";
            if (title) md += `${heading} ${title}\n\n`;
            const marker = entry.type === "ContentOrderedList" ? (i) => `${i + 1}.` : () => "-";
            (entry.items || []).forEach((item, i) => {
                const text = typeof item === "string" ? item : (item.text || "");
                md += `${marker(i)} ${htmlToPlain(text)}\n`;
            });
            return md + "\n";
        }
        case "ContentTable": {
            let md = "";
            if (title) md += `${heading} ${title}\n\n`;
            if (entry.subtitle) md += htmlToPlain(entry.subtitle) + "\n\n";
            const cols = entry.columns || [];
            const rows = entry.rows || [];
            if (cols.length) {
                md += "| " + cols.join(" | ") + " |\n";
                md += "| " + cols.map(() => "---").join(" | ") + " |\n";
                for (const row of rows) {
                    md += "| " + row.map(c => Array.isArray(c) ? c.join("; ") : htmlToPlain(String(c || ""))).join(" | ") + " |\n";
                }
            }
            if (entry.note) md += `\n*${htmlToPlain(entry.note)}*\n`;
            return md + "\n";
        }
        case "ContentTimeline": {
            let md = "";
            if (title) md += `${heading} ${title}\n\n`;
            for (const item of entry.items || []) {
                const date = item.date ? `**${item.date}** — ` : "";
                const t = item.title || "";
                const sub = item.subtitle ? `: ${htmlToPlain(item.subtitle)}` : "";
                md += `- ${date}${t}${sub}\n`;
            }
            return md + "\n";
        }
        case "ContentImage": {
            const alt = entry.alt || entry.title || "";
            const src = entry.src || entry.href || "";
            return src ? `![${alt}](${src})\n\n` : "";
        }
        case "ContentToc":
            return "";
        default:
            return "";
    }
}

function jsonPageToMarkdown (json) {
    let md = "";
    if (json.title) md += `# ${json.title}\n\n`;
    if (json.subtitle) md += htmlToPlain(json.subtitle) + "\n\n";
    for (const entry of json.content || []) {
        md += contentEntryToMarkdown(entry, 0);
    }
    return md.trim() + "\n";
}

function groupOrderKey (group) {
    // Keep a stable, readable ordering: docs first, then alphabetical.
    if (group === "docs") return "0";
    return "1" + group.toLowerCase();
}

function generateLlmsIndex (pages) {
    const rootMeta = readPageMeta(siteRoot);
    const rootJson = rootMeta ? rootMeta.json : {};
    const rootTitle = rootJson.topTitle || rootJson.title || "Site";
    const rootSubtitle = htmlToPlain(rootJson.subtitle || "");

    const groups = new Map();
    for (const pageDir of pages) {
        if (pageDir === siteRoot) continue;
        const relPath = relative(siteRoot, pageDir);
        const top = relPath.split(sep)[0];
        if (!groups.has(top)) groups.set(top, []);
        groups.get(top).push(pageDir);
    }

    const sortedGroups = [...groups.keys()].sort((a, b) =>
        groupOrderKey(a).localeCompare(groupOrderKey(b))
    );

    let txt = `# ${rootTitle}\n\n`;
    if (rootSubtitle) txt += `> ${rootSubtitle}\n\n`;

    for (const group of sortedGroups) {
        const groupDir = join(siteRoot, group);
        const groupMeta = readPageMeta(groupDir);
        const groupTitle = (groupMeta && groupMeta.json && groupMeta.json.title) || group;
        txt += `## ${groupTitle}\n\n`;

        const groupPages = groups.get(group).sort((a, b) =>
            relative(siteRoot, a).localeCompare(relative(siteRoot, b))
        );

        for (const pageDir of groupPages) {
            const meta = readPageMeta(pageDir);
            if (!meta) continue;
            const title = pageDisplayTitle(pageDir, meta);
            const subtitle = htmlToPlain(meta.json.subtitle || "");
            const url = "/" + pageUrlPath(pageDir);
            txt += `- [${title}](${url})`;
            if (subtitle) txt += `: ${subtitle}`;
            txt += "\n";
        }
        txt += "\n";
    }

    return txt;
}

function rootFirstParagraph () {
    const meta = readPageMeta(siteRoot);
    if (!meta || !meta.json || !meta.json.content) return "";
    for (const entry of meta.json.content) {
        if (entry.type === "ContentText" && entry.body) {
            const match = entry.body.match(/<p[^>]*>([\s\S]*?)<\/p>/i);
            if (match) return htmlToPlain(match[0]);
        }
    }
    return "";
}

function generateLlmsFull (pages) {
    const rootMeta = readPageMeta(siteRoot);
    const rootJson = rootMeta ? rootMeta.json : {};
    const rootTitle = rootJson.topTitle || rootJson.title || "Site";

    const sorted = [...pages].sort((a, b) => {
        if (a === siteRoot) return -1;
        if (b === siteRoot) return 1;
        return relative(siteRoot, a).localeCompare(relative(siteRoot, b));
    });

    let out = `# ${rootTitle} — Full Documentation\n\n`;
    const summary = rootFirstParagraph();
    if (summary) out += `${summary}\n\n`;
    out += "See also: /llms.txt (curated index) and /sitemap.xml.\n\n";

    for (const pageDir of sorted) {
        const meta = readPageMeta(pageDir);
        if (!meta) continue;
        const urlPath = pageUrlPath(pageDir);
        const url = "/" + urlPath;
        const pathLabel = relative(siteRoot, pageDir) || "(root)";

        out += "\n\n---\n\n";
        out += `<!-- Page: ${pathLabel} -->\n`;
        out += `Source: ${url}\n\n`;

        if (meta.rawMarkdown) {
            out += meta.rawMarkdown.trim() + "\n";
        } else {
            out += jsonPageToMarkdown(meta.json);
        }
    }

    return out;
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

function loadConfig () {
    const configPath = join(siteRoot, "llms-config.json");
    if (existsSync(configPath)) {
        return JSON.parse(readFileSync(configPath, "utf-8"));
    }
    return {};
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main () {
    const config = loadConfig();
    const siteUrl = config.siteUrl || "/";

    // Build the classic-script bundle first; pages reference it.
    const bundlePath = join(__dirname, "layout", "bundle.js");
    writeFileSync(bundlePath, buildBundle());
    console.log(`  generated: colvmn/layout/bundle.js`);

    const pages = findLayoutPages(siteRoot);
    console.log(`Static gen: found ${pages.length} layout pages under ${siteRoot}`);

    for (const pageDir of pages) {
        await generatePage(pageDir, siteUrl);
    }

    // Write sitemap.xml at site root
    const sitemap = generateSitemap(pages, siteUrl);
    writeFileSync(join(siteRoot, "sitemap.xml"), sitemap);
    console.log(`  generated: sitemap.xml (${pages.length} URLs)`);

    // Write llms.txt (curated index for LLMs)
    const llmsIndex = generateLlmsIndex(pages);
    writeFileSync(join(siteRoot, "llms.txt"), llmsIndex);
    console.log("  generated: llms.txt");

    // Write llms-full.txt (full content for LLMs)
    const llmsFull = generateLlmsFull(pages);
    writeFileSync(join(siteRoot, "llms-full.txt"), llmsFull);
    console.log("  generated: llms-full.txt");

    console.log(`Static gen: done (${pages.length} pages).`);
}

main().catch(e => {
    console.error("Static gen failed:", e);
    process.exit(1);
});
